server {
    listen 80;
    server_name garb-anzo.tech;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
     listen 443 ssl;
    server_name garb-anzo.tech;

    ssl_certificate /etc/letsencrypt/live/garb-anzo.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/garb-anzo.tech/privkey.pem;

    # SSL Settings (you can adjust these as needed)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers on;

    root /var/www/wordpress;
    index index.php index.html;

    location / {
        index index.php;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
