---
- name: Stop and remove all Docker containers
  shell: |
    docker ps -aq | xargs -r docker stop
    docker ps -aq | xargs -r docker rm
  ignore_errors: yes

- name: Remove all Docker images
  shell: |
    docker images -aq | xargs -r docker rmi -f
  ignore_errors: yes

- name: Remove all Docker volumes
  shell: |
    docker volume ls -q | xargs -r docker volume rm -f
  ignore_errors: yes

- name: remove inception network
  shell: |
    docker network rm inception || true
  ignore_errors: yes

- name: Remove data directory
  file:
    path: ~/data
    state: absent

- name: Remove srcs directory
  file:
    path: ~/cloud-1
    state: absent
