
services:
  database :
    image : mariadb
    container_name: mariadb
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks: 
      - inception
    build: requirements/mariadb
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
      - ./requirements/nginx/ssl:/etc/letsencrypt  
      - ./requirements/nginx/lib_letsencrypt:/var/lib/letsencrypt  
      - ./requirements/nginx/nginx-ssl:/etc/nginx/ssl
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/nginx
    ports: 
      - "443:443"
      - "80:80"
    restart: always

  wordpress :
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/wordpress
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    networks: 
      - inception
    depends_on: 
      - database
    ports: 
      - "127.0.0.1:8080:80"
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      
volumes:
  wordpress:
  mariadb:

networks:
  inception:
    name : inception
    driver : bridge
