server {

    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name garb-anzo.tech afadlane.garb-anzo.tech www.garb-anzo.tech;
    ssl_certificate     /etc/nginx/ssl/garb-anzo.tech/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/garb-anzo.tech/privkey.pem;

    root /var/www/wordpress;
    index  index.php;


    location / {
            try_files $uri $uri/ =404;
        }


    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}


server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name abouassi.duckdns.org;
    ssl_certificate     /etc/nginx/ssl/abouassi.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/abouassi.duckdns.org/privkey.pem;
    
    root /var/www/wordpress;
    index  index.php;


    location / {
            try_files $uri $uri/ =404;
        }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}