- name: Playbook to set up the cloud-1 environment
  hosts: cloud-1
  become: true

  roles:
    # - system-setup
    - certificates
    - nginx
    - wordpress
    - mariadb
    - docker-compose
    # - cleanup
