name: CI & DockerHub Push
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Debug - Check Username
        run: echo "DockerHub username: '${{ secrets.DOCKERHUB_USERNAME }}'"
        
      - name: Debug - Check Token (first 10 chars)
        run: echo "DockerHub token starts with: '$(echo '${{ secrets.DOCKERHUB_TOKEN }}' | cut -c1-10)...'"
        
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.hub.docker.com
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build & Push MariaDB Image
        uses: docker/build-push-action@v5
        with:
          context: ./roles/inception/srcs/requirements/mariadb
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mariadb:latest
          
      - name: Build & Push WordPress Image
        uses: docker/build-push-action@v5
        with:
          context: ./roles/inception/srcs/requirements/wordpress
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress:latest
          
      - name: Build & Push NGINX Image
        uses: docker/build-push-action@v5
        with:
          context: ./roles/inception/srcs/requirements/nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest